numbers = [5, 2, 1, 7, 4]
numbers.insert(0, 10)
print(numbers)
numbers.append(20)
print(numbers)
numbers.remove(1)
print(numbers)
numbers.pop()
print(numbers)
print(50 in numbers)
print(numbers.index(7))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
